### ISSUE TITLE
Loading a DDS file results in a NullReferenceException being thrown

### ISSUE THREAD

**Issue by TGEnigma** [andburn/dds-reader#3]
After stepping through the source, it seems the calculated compressed data size is 0.

The culprit lies here:
DDSImage.cs line 117: `uint bps = header.width * header.pixelformat.rgbbitcount / 8;` where rgbbitcount is 0

The header seems to be intact otherwise.

**Comment by andburn** [comment]
Hi, thanks for the report. I'll look into it soon.
Do you have the sample image that you used?

**Comment by FreeDenny9700** [comment]
I have the same problem with DDS file.
This is the file that i have used: https://mega.nz/#!iJdiiIAR!2ffh0YUjEcnneuCvOvGw13xE0Rw2_hqrGy4Oc5M4q0g

Thanks for help
