### ISSUE TITLE
Wrong interpretation of pixelformat.rgbbitcount

### ISSUE THREAD

**Issue by holmas** [andburn/dds-reader#6]
DDSImage.cs line 117: using of pixelformat.rgbbitcount unconditionally is wrong. Microsoft docu says "Number of bits in an RGB (possibly including alpha) format. Valid when dwFlags includes DDPF_RGB, DDPF_LUMINANCE, or DDPF_YUV." So, I have an dds-image with neither of these flags set and the rgbbitcount field is 0. This results in a zero-size-image - very hard to see ;)

**Comment by andburn** [comment]
Can you post that image here?

**Comment by andburn** [comment]
:new:  Project refactored to use the [Pfim](https://github.com/nickbabcock/Pfim) library as a decoder.
