### ISSUE TITLE
Issue with read\open of DXT3 file

### ISSUE THREAD

**Issue by joye-ramone** [andburn/dds-reader#7]
Hello,

I am getting strange result when reading DXT3 files. DXT5 works very well.
Original file https://www.dropbox.com/s/hv6d5ru6dwemsyr/ui_team_logo.dds?dl=0
Original file look https://i.imgur.com/to9Vj9l.png

Lib read file like this https://i.imgur.com/1B2qbJM.png

That is not only for this single file, but for all DXT3 files that I have.
Also, other editors\viewers show such files without any issues.

Do you have an idea if it is possible to fix this?

**Comment by andburn** [comment]
I couldn't maintain this project as it was, so I've simplified it and used the [Pfim](https://github.com/nickbabcock/Pfim) library as a decoder, it does a much better job. You may want to use *Pfim* directly in your own project and use mine as an example of its use.
